Student6Project/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student6Project/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>War</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/TMDB_Id__c.field-meta.xml
<CustomField>
    <fullName>TMDB_Id__c</fullName>
    <label>TMDB Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Student6Project/force-app/main/default/classes/MovieDataUploadController.cls
public with sharing class MovieDataUploadController {

    @AuraEnabled
    public static Integer uploadMovieData(String contentDocumentId) {
        ContentVersion contentVersion = [SELECT VersionData FROM ContentVersion WHERE ContentDocumentId = :contentDocumentId LIMIT 1];
        String jsonContent = contentVersion.VersionData.toString();

        Set<String> existingTmdbIds = new Set<String>();
        for (Movie__c existingMovie : [SELECT TMDB_Id__c FROM Movie__c WHERE TMDB_Id__c != null]) {
            existingTmdbIds.add(existingMovie.TMDB_Id__c);
        }
        List<Movie__c> moviesToInsert = new List<Movie__c>();
        List<Object> movieDataList = (List<Object>) JSON.deserializeUntyped(jsonContent);
        for (Object movieDataObj : movieDataList) {
            Map<String, Object> movieData = (Map<String, Object>) movieDataObj;
            String tmdbId = String.valueOf(movieData.get('tmdb_id'));

            if (existingTmdbIds.contains(tmdbId)) {
                continue;
            }
            Movie__c movie = new Movie__c();
            movie.Title__c = (String) movieData.get('name');
            movie.Budget__c = (movieData.get('budget') != null) ? Decimal.valueOf(String.valueOf(movieData.get('budget'))) : null;
            movie.Revenue__c = (movieData.get('revenue') != null) ? Decimal.valueOf(String.valueOf(movieData.get('revenue'))) : null;
            movie.Genre__c = (String) movieData.get('genre');
            movie.Rating__c = (movieData.get('rating') != null) ? Decimal.valueOf(String.valueOf(movieData.get('rating'))) : null;
            movie.TMDB_Id__c = tmdbId;
            movie.TMDBSyncDate__c = Date.today();
            movie.Description__c = (String) movieData.get('overview');
            
            moviesToInsert.add(movie);
        }

        if (!moviesToInsert.isEmpty()) {
            insert moviesToInsert;
        }
        
        return moviesToInsert.size();
    }
}