Student6Project/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student6Project/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Poster_URL__c.field-meta.xml
<CustomField>
    <fullName>Poster_URL__c</fullName>
    <label>Poster URL</label>
    <type>Url</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/classes/FetchMovieDataQueueable.cls
public class FetchMovieDataQueueable implements Queueable, Database.AllowsCallouts {
    private List<String> tmdbIds;
    private List<Id> movieRecordIds;
    private Integer startIndex;
    private Integer batchSize;

    public FetchMovieDataQueueable(List<String> tmdbIds, List<Id> movieRecordIds, Integer startIndex, Integer batchSize) {
        this.tmdbIds = tmdbIds;
        this.movieRecordIds = movieRecordIds;
        this.startIndex = startIndex;
        this.batchSize = batchSize;
    }

    public void execute(QueueableContext context) {
        Integer endIndex = Math.min(startIndex + batchSize, tmdbIds.size());

        List<String> currentBatchTmdbIds = new List<String>();
        List<Id> currentBatchMovieRecordIds = new List<Id>();

        for (Integer i = startIndex; i < endIndex; i++) {
            currentBatchTmdbIds.add(tmdbIds[i]);
            currentBatchMovieRecordIds.add(movieRecordIds[i]);
        }

        List<Movie__c> movieRecordsToUpdate = new List<Movie__c>();
        tmdb tmdbService = new tmdb();

        for (Integer i = 0; i < currentBatchTmdbIds.size(); i++) {
            tmdb.tmdbMovieResponse movieData = tmdbService.getMovieById(currentBatchTmdbIds[i]);
            if (movieData != null) {
                Movie__c movieRecord = new Movie__c(Id = currentBatchMovieRecordIds[i]);
                movieRecord.Description__c = movieData.overview;
                movieRecord.Title__c = movieData.original_title;
                movieRecord.Poster_URL__c ='https://image.tmdb.org/t/p/w600_and_h900_bestv2' + movieData.poster_path;
                movieRecord.Budget__c = movieData.budget;
                movieRecord.Rating__c = movieData.vote_average;
                movieRecord.Revenue__c = movieData.revenue;
                movieRecord.TMDBSyncDate__c = Date.today();
                movieRecordsToUpdate.add(movieRecord);
            }
        }

        if (!movieRecordsToUpdate.isEmpty()) {
            update movieRecordsToUpdate;
        }

        if (endIndex < tmdbIds.size()) {
            FetchMovieDataQueueable nextBatch = new FetchMovieDataQueueable(tmdbIds, movieRecordIds, endIndex, batchSize);
            System.enqueueJob(nextBatch);
        }
    }
}