Student6Project/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student6Project/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>War</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/classes/tmdb.cls
public with sharing class tmdb {
    private static final String API_KEY = '5bfef77f0d03fea766a8ab7ddfe11ab1';
    private static final String API_KEY_PARAM_NAME = 'api_key';
    private static final String API_VERSION = '3';
    private static final String BASE_URL = 'https://api.themoviedb.org/';

    public String authQueryParameter {
        get {
            return API_KEY_PARAM_NAME + '=' + API_KEY;
        }
    }

    public String buildResourceUrl(String resourceName) {
        return BASE_URL + API_VERSION + resourceName;
    }

    public HttpRequest authenticateRequest(HttpRequest request) {
        String endpoint = request.getEndpoint();
        if (endpoint.contains('?')) {
            endpoint += '&' + authQueryParameter;
        } else {
            endpoint += '?' + authQueryParameter;
        }
        request.setEndpoint(endpoint);
        return request;
    }

    public tmdbMovieResponse getMovieById(String movieId) {
        String resourceName = '/movie/' + movieId + '?language=en-US';
        String endpoint = buildResourceUrl(resourceName);
        HttpRequest request = new HttpRequest();
        request.setMethod('GET');
        request.setEndpoint(endpoint);
        request = authenticateRequest(request);
        Http http = new Http();
        HttpResponse response = http.send(request);
        System.debug('Response Body: ' + response.getBody());
        tmdbMovieResponse movieData = (tmdbMovieResponse) JSON.deserialize(response.getBody(), tmdbMovieResponse.class);
        return movieData;
    }

    public void saveMovieDataToSalesforce(String movieId, Id recordId) {
        tmdbMovieResponse movieData = getMovieById(movieId);
        Movie__c movieRecord = [SELECT Id, Genre__c FROM Movie__c WHERE Id = :recordId LIMIT 1];
        List<String> genres = new List<String>();
        for (tmdbGenre genre : movieData.genres) {
            genres.add(genre.name);
            System.debug('Genre received: ' + genre.name);
        }
        
        movieRecord.Genre__c = String.join(genres, ', ');
        movieRecord.Title__c = movieData.original_title;
        movieRecord.Description__c = movieData.overview;
        movieRecord.Rating__c = movieData.vote_average;
        movieRecord.Budget__c = movieData.budget;
        movieRecord.Revenue__c = movieData.revenue;
        movieRecord.TMDBSyncDate__c = Date.today();
        
        update movieRecord;
    }

    public class tmdbMovieResponse {
        public String overview;
        public String original_title;
        public Long revenue;
        public Double vote_average;
        public String poster_path;
        public Integer budget;
        public List<tmdbGenre> genres;
    }

    public class tmdbGenre {
        public Integer id;
        public String name;
    }
}