Student6Project/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student6Project/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>War</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <type>Lookup</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/TMDB_Id__c.field-meta.xml
<CustomField>
    <fullName>TMDB_Id__c</fullName>
    <label>TMDB Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Student6Project/force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <label>Script</label>
    <nameField>
        <label>Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student6Project/force-app/main/default/objects/Script__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Picking the right genre can generate a lot of interest!</description>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre</valueSetName>
    </valueSet>
</CustomField>

Student6Project/force-app/main/default/classes/MovieDataImport.cls
public class MovieDataImport {
    public static void importMovies(String jsonData) {
        List<MovieDataStructures.MovieJSON> movies = 
            (List<MovieDataStructures.MovieJSON>) JSON.deserialize(jsonData, List<MovieDataStructures.MovieJSON>.class);

        Set<String> tmdbIds = new Set<String>();
        Set<String> scriptIds = new Set<String>();
        
        for (MovieDataStructures.MovieJSON movieData : movies) {
            tmdbIds.add(movieData.tmdb_id);
            if (movieData.script != null) {
                scriptIds.add(movieData.script.id);
            }
        }

        Map<String, Movie__c> existingMoviesMap = new Map<String, Movie__c>();
        for (Movie__c movie : [SELECT Id, TMDB_Id__c FROM Movie__c WHERE TMDB_Id__c IN :tmdbIds]) {
            existingMoviesMap.put(movie.TMDB_Id__c, movie);
        }

        Map<String, Script__c> existingScriptsMap = new Map<String, Script__c>();
        if (!scriptIds.isEmpty()) {
            for (Script__c script : [SELECT Id, LegacyId__c FROM Script__c WHERE LegacyId__c IN :scriptIds]) {
                existingScriptsMap.put(script.LegacyId__c, script);
            }
        }

        List<Movie__c> moviesToInsert = new List<Movie__c>();
        List<Script__c> scriptsToInsert = new List<Script__c>();
        Map<String, String> scriptMap = new Map<String, String>();
        // test
        for (MovieDataStructures.MovieJSON movieData : movies) {
            if (existingMoviesMap.containsKey(movieData.tmdb_id)) {
                System.debug('Movie with tmdb_id ' + movieData.tmdb_id + ' already exists. Skipping.');
                continue; 
            }
        
            Movie__c movieRecord = new Movie__c();
            movieRecord.LegacyId__c = movieData.id;
            movieRecord.Title__c = movieData.name;
            movieRecord.TMDB_Id__c = movieData.tmdb_id;
            movieRecord.Genre__c = movieData.genre;
            movieRecord.Rating__c = movieData.rating;
            movieRecord.Budget__c = movieData.budget;
            movieRecord.Revenue__c = movieData.revenue;
            movieRecord.Description__c = movieData.script != null ? movieData.script.description : null;
        
            if (movieData.script != null) {
                if (existingScriptsMap.containsKey(movieData.script.id)) {
                    movieRecord.Script__c = existingScriptsMap.get(movieData.script.id).Id;
                } else {
                    Script__c scriptRecord = new Script__c();
                    scriptRecord.LegacyId__c = movieData.script.id;
                    scriptRecord.Title__c = movieData.script.name;
                    scriptRecord.Description__c = movieData.script.description;
                    scriptsToInsert.add(scriptRecord);
                    scriptMap.put(movieData.script.id, null);
                }
            }
        
            moviesToInsert.add(movieRecord);
        }

        if (!moviesToInsert.isEmpty()) {
            insert moviesToInsert;
        }

        if (!scriptsToInsert.isEmpty()) {
            insert scriptsToInsert;

            for (Script__c script : scriptsToInsert) {
                scriptMap.put(script.LegacyId__c, script.Id);
            }

            List<Movie__c> moviesToUpdate = new List<Movie__c>();
            for (Movie__c movie : moviesToInsert) {
                if (movie.Script__c == null && scriptMap.containsKey(movie.LegacyId__c)) {
                    movie.Script__c = scriptMap.get(movie.LegacyId__c);
                    moviesToUpdate.add(movie);
                }
            }

            if (!moviesToUpdate.isEmpty()) {
                update moviesToUpdate;
            }
        }

        System.debug('Movies inserted successfully: ' + moviesToInsert.size());
    }
}