Student6Project/force-app/main/default/objects/Client_Review__c/Client_Review__c.object-meta.xml
<CustomObject>
    <label>Client Review</label>
    <nameField>
        <displayFormat>Cli-{0000}</displayFormat>
        <label>Client Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student6Project/force-app/main/default/objects/Client_Review__c/fields/MovieLookUp__c.field-meta.xml
<CustomField>
    <fullName>MovieLookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MovieLookUp</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Client Reviews</relationshipLabel>
    <relationshipName>Client_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

Student6Project/force-app/main/default/objects/Client_Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <inlineHelpText>From 1 to 5</inlineHelpText>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Student6Project/force-app/main/default/objects/Client_Review__c/fields/Review_Text__c.field-meta.xml
<CustomField>
    <fullName>Review_Text__c</fullName>
    <label>Review Text</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

Student6Project/force-app/main/default/classes/ReviewController.cls
public with sharing class ReviewController {
    @AuraEnabled(cacheable=false)
    public static List<Client_Review__c> getReviewsByMovie(Id movieId) {
        return [SELECT Id, Client_Name__c, Review_Date__c, Review_Text__c, Rating__c FROM Client_Review__c WHERE MovieLookUp__c = :movieId ORDER BY Review_Date__c DESC];
    }

    @AuraEnabled
    public static void addReview(Client_Review__c review) {
        insert review;
    }
}