Student6Project/force-app/main/default/objects/Client_Review__c/Client_Review__c.object-meta.xml
<CustomObject>
    <label>Client Review</label>
    <nameField>
        <displayFormat>Cli-{0000}</displayFormat>
        <label>Client Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student6Project/force-app/main/default/objects/Client_Review__c/fields/MovieLookUp__c.field-meta.xml
<CustomField>
    <fullName>MovieLookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MovieLookUp</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Client Reviews</relationshipLabel>
    <relationshipName>Client_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

Student6Project/force-app/main/default/objects/Client_Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <inlineHelpText>From 1 to 5</inlineHelpText>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>MOV-{0000}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student6Project/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>War</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/objects/Movie__c/fields/Rating_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Rating_Calculated__c</fullName>
    <formula>Rating__c * 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating (Calculated)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Student6Project/force-app/main/default/classes/ReviewAnalytics.cls
public class ReviewAnalytics {

    public static Decimal calculateBudgetRatingCorrelation() {
        List<Movie__c> movies = [SELECT Id, Budget__c, Rating_Calculated__c FROM Movie__c WHERE Budget__c != null AND Rating_Calculated__c != null];
        
        if (movies.isEmpty()) return null;

        Decimal avgBudget = 0;
        Decimal avgRating = 0;
        for (Movie__c movie : movies) {
            avgBudget += movie.Budget__c;
            avgRating += movie.Rating_Calculated__c;
        }
        avgBudget /= movies.size();
        avgRating /= movies.size();

        Decimal numerator = 0;
        Decimal denominatorBudget = 0;
        Decimal denominatorRating = 0;

        for (Movie__c movie : movies) {
            Decimal budgetDiff = movie.Budget__c - avgBudget;
            Decimal ratingDiff = movie.Rating_Calculated__c - avgRating;
            numerator += budgetDiff * ratingDiff;
            denominatorBudget += budgetDiff * budgetDiff;
            denominatorRating += ratingDiff * ratingDiff;
        }

        Decimal denominator = Math.sqrt(denominatorBudget) * Math.sqrt(denominatorRating);

        if (denominator == 0) return 0;

        return (numerator / denominator).setScale(4, RoundingMode.HALF_UP);
    }

    public static Map<String, Map<Integer, Integer>> getRatingDistribution() {
        List<Client_Review__c> reviews = [SELECT MovieLookUp__r.Title__c, Rating__c FROM Client_Review__c];

        Map<String, Map<Integer, Integer>> movieRatingDistribution = new Map<String, Map<Integer, Integer>>();

        for (Client_Review__c review : reviews) {
            String movieName = review.MovieLookUp__r.Title__c;
            Integer rating = Integer.valueOf(review.Rating__c);

            if (!movieRatingDistribution.containsKey(movieName)) {
                movieRatingDistribution.put(movieName, new Map<Integer, Integer>());
            }

            Map<Integer, Integer> ratingDist = movieRatingDistribution.get(movieName);

            if (!ratingDist.containsKey(rating)) {
                ratingDist.put(rating, 0);
            }

            ratingDist.put(rating, ratingDist.get(rating) + 1);
        }

        return movieRatingDistribution;
    }

    public static Map<String, Decimal> getAverageRatingByGenre() {
        Map<String, Decimal> genreRatingSums = new Map<String, Decimal>();
        Map<String, Integer> genreCounts = new Map<String, Integer>();

        List<Client_Review__c> reviews = [SELECT MovieLookUp__r.Genre__c, Rating__c FROM Client_Review__c];

        for (Client_Review__c review : reviews) {
            if (review.MovieLookUp__r.Genre__c != null) {
                List<String> genres = review.MovieLookUp__r.Genre__c.split(';');
                for (String genre : genres) {
                    if (!genreRatingSums.containsKey(genre)) {
                        genreRatingSums.put(genre, 0);
                        genreCounts.put(genre, 0);
                    }
                    genreRatingSums.put(genre, genreRatingSums.get(genre) + Decimal.valueOf(review.Rating__c));
                    genreCounts.put(genre, genreCounts.get(genre) + 1);
                }
            }
        }

        Map<String, Decimal> averageRatingsByGenre = new Map<String, Decimal>();
        for (String genre : genreRatingSums.keySet()) {
            if (genreCounts.get(genre) > 0) {
                averageRatingsByGenre.put(genre, (genreRatingSums.get(genre) / genreCounts.get(genre)).setScale(4, RoundingMode.HALF_UP));
            }
        }

        return averageRatingsByGenre;
    }

    public static void displayExtendedAnalytics() {
        Decimal correlation = calculateBudgetRatingCorrelation();
        System.debug('Correlation between Budget and Rating: ' + String.valueOf(correlation != null ? correlation : 0));

        Map<String, Map<Integer, Integer>> ratingDistribution = getRatingDistribution();
        for (String movie : ratingDistribution.keySet()) {
            System.debug('Rating distribution for ' + movie + ': ' + ratingDistribution.get(movie));
        }

        Map<String, Decimal> averageRatingsByGenre = getAverageRatingByGenre();
        if (averageRatingsByGenre.isEmpty()) {
            System.debug('No reviews available to display analytics.');
        } else {
            for (String genre : averageRatingsByGenre.keySet()) {
                System.debug('Average rating for genre ' + genre + ': ' + averageRatingsByGenre.get(genre));
            }
        }
    }
}